[tool.poetry]
name = "corneto"
version = "0.9.0-alpha.7"
description = "CORNETO: CORe NETwork Optimizer, a MILP optimization library for Biochemical Networks"
authors = ["Pablo Rordriguez-Mier <pablo.rodriguez-mier@uni-heidelberg.de>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Mathematics"
]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/saezlab/corneto/"
homepage = "https://github.com/saezlab/corneto/"
include = ["LICENSE"]

[tool.poetry.dependencies]
python = ">=3.7 <3.11"
numpy = "^1.16"
cvxpy = {version = "^1.2.1", optional = true}
cylp = {version = "^0.91.5", optional = true}
networkx = {version = "^2.7.1", optional = true}
PICOS = {version = "^2.4.1", optional = true}
matplotlib = {version = "^3.5.2", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"
pep8 = "^1.7.1"
mypy = "^0.942"
black = "^22.3.0"
PICOS = "^2.4.1"
matplotlib = "^3.5.2"
mkdocs-material = "^7.2.1"
mkdocstrings = "^0.15.2"
cvxpy = "^1.2.1"

[tool.poetry.extras]
cvxpy = ["cvxpy"]
picos = ["PICOS"]
all_backends = ["cvxpy", "PICOS"]
gurobi = ["gurobipy", "PICOS"]
cbc = ["cvxpy", "cylp"]
full = ["cvxpy", "PICOS", "matplotlib", "networkx"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

