[tool.poetry]
name = "corneto"
version = "1.0.0-alpha.0"
description = "CORNETO: A Unified Omics-Driven Framework for Network Inference"
authors = ["Pablo Rordriguez-Mier <pablo.rodriguez-mier@uni-heidelberg.de>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3"
]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/saezlab/corneto/"
homepage = "https://github.com/saezlab/corneto/"
packages = [
    { include = "corneto"},
]

[tool.poetry.dependencies]
python = ">=3.9 <4"
numpy = ">=1.26.0"
cvxpy = {version = "^1.4.0", optional = true}
PICOS = {version = "^2.4.1", optional = true}
gurobipy = {version = "^11.0.0",  optional = true}
scipy = {version = ">=1.12.0", optional = true}
pyscipopt = {version = "^5.0.0", optional = true}
graphviz = {version = "^0.20.1", optional = true}
cobra = {version = "^0.29.0", optional = true}
networkx = {version = "^3.2.1", optional = true}

[tool.poetry.group.dev.dependencies]
scipy = ">=1.12.0"
pyscipopt = "^5.0.0"
graphviz = "^0.20.1"
cobra = "^0.29.0"
networkx = "^3.2.1"
black = "^23.3.0"
ipython = "^8.7.0"
ipykernel = "^6.23.1"
PICOS = "^2.4.1"
matplotlib = "^3.5.2"
cvxpy = "^1.4.0"
sphinx = ">=5.0"
myst-parser = "^0.18.1"
pydata-sphinx-theme = "^0.15.2"
sphinxcontrib-napoleon = "^0.7"
sphinxcontrib-bibtex = "^2.5.0"
sphinx-mermaid = "^0.0.8"
sphinx-design = "^0.4.1"
sphinxcontrib-mermaid = "^0.9.2"
sphinx-favicon = "^1.0.1"
myst-nb = "^0.17.2"
sphinx-autodoc-typehints = "^1.21.8"
sphinx-hoverxref = "^1.3.0"
pytest = "^8.1.1"


[tool.poetry.extras]
os = ["cvxpy", "pyscipopt", "scipy"]
default = ["cvxpy", "scipy", "gurobipy"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

