name: Build and Deploy Docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Build Docs
        run: |
          cd docs
          poetry run make html

      - name: Prepare Deployment
        run: |
          touch ./docs/_build/html/.nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set Destination Directory
        id: set-dest-dir
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=dir::"
          else
            echo "::set-output name=dir::dev"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: ${{ steps.set-dest-dir.outputs.dir }}
